name: Clojure CI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    
    concurrency: ci-${{ github.ref }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        lein: 2.9.8
    - name: Get leiningen version
      run: lein -v
    - name: Install dependencies
      working-directory: ./crudy
      run: lein deps
    - name: Run tests
      working-directory: ./crudy
      run: lein test
    - name: Production build with lein-shadow
      working-directory: ./crudy
      run: lein prod
    - name: Copy static assets
      working-directory: ./crudy
      run: |
        mkdir prod
        cp -r node_modules/@elastic/eui/es/components/icon/* prod/
        cp -r resources/public/* prod/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: crudy/prod
